# Generated by Django 4.2.29 on 2026-03-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentskill',
            name='personality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
